---
# This playbook is used to ping test all the network devices

# Play 1


- hosts: ALLDEVICES
  gather_facts: false
  connection: local

  vars:
    cli:
      username: camara
      password: camara

  tasks:

    - name: ping test for network
      ios_command:
        provider: "{{ cli }}"
        commands:
          - ping 192.168.5.1 repeat 5
          - ping 192.168.5.2 repeat 5

      register: print_output


    - name: print output to screen
      debug:
        var=print_output.stdout_lines
